### ISSUE TITLE
Parametrize tools via config file

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/miRNA_processing#5]
Give the possibility of parametrize tools via config file, i.e:

``` yaml
tools:
    cutadapt:
        adapter_sequence: AGCTACGATCGACTG
        min_qual: 10
...
```
